### ISSUE TITLE
pyqtgraph 0.11.0 is out on anaconda main repo

### ISSUE THREAD

**Issue by ksunden** [labscript-suite/vendored-conda-builds#3]
I saw some references to wanting to remove pyqtgraph once it was released to anaconda.

I am a pyqtgraph maintainer (I was the one to actually release 0.11.0 to pypi and conda forge, which then filtered up to the anaconda main repo).

P.S. any chance I could convince you to get pydaqmx on conda-forge? You have the best conda package (only one that is up to date and properly noarch), and I use it in my lab, would prefer to stay all on one channel.

**Comment by chrisjbillington** [comment]
Thanks! I've removed pyqtgraph from the list of packages built here.

I don't have much interest in maintaining packages on conda-forge, but you are free to take the recipe (it is extremely simple) if you want to do so yourself. We don't maintain recipes, they are generated from setuptools projects using `setuptools-conda` - the below is what it generates when building PyDAQmx, though I've replaced the local path with the URL of the tarball.

```yaml
package:
  name: pydaqmx
  version: 1.4.3

source:
  url: https://pypi.io/packages/source/i/PyDAQmx/PyDAQmx-{{ version }}.tar.gz
  sha256: cf8161b5451daeb0d8032ae18197abaaab3970926f6896de10f722a6d30615fd

build:
  script: {{ PYTHON }} -m pip install .
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
    - wheel

  run:
    - python

about:
  home: http://pythonhosted.org/PyDAQmx/
  summary: 'Interface to the National Instruments PyDAQmx driver'
  license: 'This software can be used under one of the following two licenses: (1) The BSD license. (2) Any other license, as long as it is obtained from the original author.'

```
